# Generated by Django 3.0 on 2020-06-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='Booking_Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='search',
            name='Select_Place',
            field=models.CharField(choices=[('Hyderabad', 'Hyd'), ('Anantapur', 'ATP'), ('Bangalore', 'B'), ('Pune', 'P'), ('Chennai', 'C')], max_length=25),
        ),
    ]
